name: foodify
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+9
  fluid_action_card: ^1.0.0+4
  video_player: ^2.2.19
  hexcolor: ^2.0.6
  transparent_image: ^2.0.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  curved_nav_bar: ^0.0.2
  tflite: ^1.1.2
  basic_utils: ^4.2.0
  fading_edge_scrollview: ^2.0.1
  getwidget: ^2.0.5
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  cloud_firestore_web: ^2.6.10
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  share_plus: ^4.0.3
  fancy_drawer: ^2.0.0
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #material_floating_search_bar: ^0.2.6
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
    - assets/images/cuisine/
    - assets/fonts/
    - assets/tflite/ssd_mobilenet.tflite
    - assets/tflite/ssd_mobilenet.txt
    - assets/tflite/yolov2_tiny.tflite
    - assets/tflite/yolov2_tiny.txt
    - assets/tflite/model_unquant.tflite
    - assets/tflite/labels.txt
    - assets/tflite/model.tflite
    - assets/tflite/dict.txt

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

    - family: Open Sans
      fonts:
        - asset: assets/fonts/opensansbold700.ttf
          weight: 700
        - asset: assets/fonts/opensansregular400.ttf
          weight: 400
        - asset: assets/fonts/opensanslight300.ttf
          weight: 300
        - asset: assets/fonts/opensanssemibold600.ttf
          weight: 600

    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfairdisplaybold700.ttf
          weight: 700
        - asset: assets/fonts/playfairdisplayregular400.ttf
          weight: 400

    - family: Lora
      fonts:
        - asset: assets/fonts/lorabold700.ttf
          weight: 700
        - asset: assets/fonts/loraregular400.ttf
          weight: 400

    - family: Oswald
      fonts:
        - asset: assets/fonts/oswaldlight300.ttf
          weight: 300
    - family: Poppins

      fonts:
        - asset: assets/fonts/poppinsbold700.ttf
          weight: 700

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
